services:
  scraper:
    build: .
    container_name: scraper_Container
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - ./hotel_images:/usr/src/app/hotel_images
    working_dir: /usr/src/app
    depends_on:
      - postgres
    networks:
      - app_network
    environment:
      - DATABASE_URL=postgresql+psycopg2://aa_nadim:aa_nadim123@postgres:5432/scraping_db
    command: ["scrapy", "crawl", "tripCrawler"]


  postgres:
    image: postgres:latest
    container_name: postgresDB_Container
    environment:
      - POSTGRES_USER=aa_nadim
      - POSTGRES_PASSWORD=aa_nadim123
      - POSTGRES_DB=scraping_db
    ports:
      - "9000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U aa_nadim"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_Container
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - app_network


  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_Container
    ports:
      - "9443:9443"
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  
volumes:
  postgres_data:
  pgadmin_data:
  portainer-data:

networks:
  app_network:
    driver: bridge
